/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Student;
import model.Subject;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import presenter.IEditPresenter;

/**
 *
 * @author traig
 */
public class EditView extends javax.swing.JFrame implements IEditView{
    
    /**
     * Creates new form EditView
     */
    
   public boolean isEditable;
    IEditPresenter iEditPresenter;
     int oldId;       
    public EditView(boolean isEdit) {
        initComponents();
        this.isEditable = isEdit;
        if(!this.isEditable){
            editBtn.setText("ADD");
        }
           buttonGroup1.add(male);
           buttonGroup1.add(female);
           //System.out.println(buttonGroup1.getSelection().getSelectedObjects());;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student1 = new model.Student();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        className = new javax.swing.JTextField();
        birth = new javax.swing.JTextField();
        math = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        programming = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dbms = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        otomata = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        english = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        networking = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Title");

        jLabel1.setText("STUDENT ID");

        jLabel2.setText("FULL NAME");

        jLabel3.setText("GENDER");

        jLabel4.setText("BIRTH");

        jLabel5.setText("ADDRESS");

        jLabel6.setText("CLASS");

        jLabel7.setText("MATH");

        editBtn.setText("UPDATE");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("PROGRAMMING");

        jLabel10.setText("DBMS");

        jLabel11.setText("OTOMATA");

        jLabel12.setText("ENGLISH");

        jLabel13.setText("NETWORKING COMPUTER");

        male.setText("MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setText("FEMALE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(otomata, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(dbms, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(math, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(className, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(female))
                                        .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(programming, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn)
                            .addComponent(networking, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(className, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(math, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male)
                        .addComponent(female)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otomata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(networking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(editBtn)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        
        //check valid data
        if(!isEditable)
        add();
        else update();
    }//GEN-LAST:event_editBtnActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed


    @Override
    public void add() {
        Student student = new Student(Integer.valueOf(studentid.getText()), fullname.getText(),male.isSelected()?"male": "female",
                birth.getText(), address.getText(), className.getText(), null);
         List<Subject> listSubjects = new ArrayList<>();
          List<List<String>> results =new ArrayList<>();
           List<String> pointList = new ArrayList<>();
           System.out.println(student.getBirth());
          pointList.add(math.getText());
         pointList.add( programming.getText());
          pointList.add( dbms.getText());
          pointList.add(otomata.getText());
          pointList.add( english.getText());
          pointList.add( networking.getText());
          results.add(pointList);
          results.add(pointList);
          System.out.println(results.size());
          listSubjects.add(new Subject(results.get(0).get(0), Float.valueOf(results.get(1).get(0))));
           listSubjects.add(new Subject(results.get(0).get(1), Float.valueOf(results.get(1).get(1))));
           listSubjects.add(new Subject(results.get(0).get(2), Float.valueOf(results.get(1).get(2))));
        listSubjects.add(new Subject(results.get(0).get(3), Float.valueOf(results.get(1).get(2))));
         listSubjects.add(new Subject(results.get(0).get(4), Float.valueOf(results.get(1).get(4))));
          listSubjects.add(new Subject(results.get(0).get(5), Float.valueOf(results.get(1).get(5))));
                student.setListSubjects(listSubjects);
        this.iEditPresenter.addStudent(student);
        this.iEditPresenter.addResult(student.getStudentid(),results);
        this.iEditPresenter.sendData(student, results , isEditable);
        OnSuccess();
        studentid.setText("");
        fullname.setText("");
        birth.setText("");
        address.setText("");
        className.setText("");
        math.setText("");
        programming.setText("");
         dbms.setText("");
        english.setText("");
         otomata.setText("");
        networking.setText("");
        
    }

    @Override
    public void update() {
          Student student = new Student(Integer.valueOf(studentid.getText()), fullname.getText(),male.isSelected()?"male": "female",
                birth.getText(), address.getText(), className.getText(), null);
          List<Subject> listSubjects = new ArrayList<>();
          List<List<String>> results =this.iEditPresenter.loadResults();
          results.get(1).set(0, math.getText());
          results.get(1).set(1, programming.getText());
          results.get(1).set(2, dbms.getText());
          results.get(1).set(3, otomata.getText());
          results.get(1).set(4, english.getText());
          results.get(1).set(5, networking.getText());
          
          listSubjects.add(new Subject(results.get(0).get(0), Float.valueOf(results.get(1).get(0))));
           listSubjects.add(new Subject(results.get(0).get(1), Float.valueOf(results.get(1).get(1))));
           listSubjects.add(new Subject(results.get(0).get(2), Float.valueOf(results.get(1).get(2))));
        listSubjects.add(new Subject(results.get(0).get(3), Float.valueOf(results.get(1).get(2))));
         listSubjects.add(new Subject(results.get(0).get(4), Float.valueOf(results.get(1).get(4))));
          listSubjects.add(new Subject(results.get(0).get(5), Float.valueOf(results.get(1).get(5))));
                student.setListSubjects(listSubjects);
        this.iEditPresenter.updateResult(oldId, Integer.valueOf(studentid.getText()), results);
        this.iEditPresenter.updateStudent(oldId,student);
         this.iEditPresenter.sendData(student, results , isEditable);
    }
    
    @Override
    public void showStudent(Student student,List<List<String>> results) {
            oldId = student.getStudentid();
            System.out.println(oldId);
           studentid.setText(Integer.toString(student.getStudentid()));
            fullname.setText(student.getFullname());
            birth.setText(student.getBirth());
            address.setText(student.getAddress());
            className.setText((student.getClassName()));
            math.setText(results.get(1).get(0));
            programming.setText(results.get(1).get(1));
            dbms.setText(results.get(1).get(2));
            otomata.setText(results.get(1).get(3));
            english.setText(results.get(1).get(4));
            networking.setText(results.get(1).get(5));
            if(student.getGender().equals("male"))
                male.setSelected(true);
            else female.setSelected(true);
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birth;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField className;
    private javax.swing.JTextField dbms;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField english;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField math;
    private javax.swing.JTextField networking;
    private javax.swing.JTextField otomata;
    private javax.swing.JTextField programming;
    private model.Student student1;
    private javax.swing.JTextField studentid;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnSuccess() {
        //show dialog to infor to user .
        
        JOptionPane.showMessageDialog(getOwner(),
    "EDITING SUCCESSFULLY!");
        OnClose();
    }

    @Override
    public void OnFail() {
         JOptionPane.showMessageDialog(getOwner(),
    "YOU HAVE ENTERED SOMETHINGS WRONG!", "ERROR",JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public IEditPresenter getPresenter() {

        return this.iEditPresenter;
    }

    @Override
    public void setPresenter(IEditPresenter iEditPresenter) {
        this.iEditPresenter = iEditPresenter;
     }

    @Override
    public void OnShow() {
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        
    }

    @Override
    public void OnClose() {
           setVisible(false);
    }

    public boolean isIsEdit() {
        return isEditable;
    }

    public void setIsEdit(boolean isEdit) {
        this.isEditable = isEdit;
    }
    
    

    
}
